export const SIAM_LLM_WIKI = `# Structure Guide: siam-qa-automation

> Auto-generated by QA Test Generator

## Overview

| Property | Value |
|---|---|
| Language | mixed |
| Architecture | Locators → Page Objects → Tests (Smoke) → Tests (Regression) → Helpers → Flows → Support → Fixtures → Utils → Types |
| Code Patterns | class-based Page Objects, singleton instance export, custom commands (getByCy), separate locator imports, exported helper functions, as const for literal types, UPPER_SNAKE_CASE constants |
| Custom Commands | 13 |

## Directory Tree

\`\`\`
Tutorial/
  01-پیش‌نیازها-و-راه‌اندازی.md
  02-ساختار-پروژه-و-معماری.md
  03-Page-Object-Model.md
  04-Cypress-Commands-و-Support.md
  05-BDD-با-Cucumber.md
  06-گزارش‌گیری-با-Allure.md
  07-CICD-با-Azure-Pipelines.md
  08-مدیریت-داده-و-دیتابیس.md
  09-بهترین-روش‌ها-و-استانداردها.md
  10-ایجاد-پروژه-جدید.md
  README.md
  confluence/
    01-معرفی-پروژه.md
    02-راهنمای-نصب-و-راه‌اندازی.md
    03-معماری-پروژه.md
    04-Page-Object-Model.md
    05-دستورات-سفارشی-Cypress.md
    06-BDD-و-Cucumber.md
    07-گزارش‌گیری-Allure.md
    08-CICD-Azure-Pipelines.md
    09-مدیریت-داده-و-دیتابیس.md
    10-بهترین-روش‌ها-و-استانداردها.md
    11-اسکریپت‌ها-و-اتوماسیون.md
    README.md
  create-cypress-project.sh
  docs/
    setup-allure.sh
    آموزش-گزارش-گیری-Allure.docx
azure-pipelines.yml
cypress/
  e2e/
    locators/
      addressManagementLocators.ts
      adminWorkSpaceLocators/
        eventAcceptionLocators.ts
      banServiceLocators.ts
      basicInformation/
        other/
          forbiddenCountryDivisionLocators.ts
          licenseLocators.ts
          universitieLocators.ts
        users/
          accessLevelLocators.ts
          organizationalChartLocators.ts
      camp/
        campAdmissionwithReturnPermitLocators.ts
        expiredInCampLocators.ts
        keepInCampLocators.ts
      campPageLocators.ts
      correctionOfIdentityInformationLocators.ts
      crimeLocators.ts
      enterBorderLocators.js
      enterToCountryLocators.ts
      exclusionListLocators.js
      foreignNationalServices/
        selfIntroducingLocators.ts
      generalLocators/
        scanFileLocators.js
      guestCity/
        createDischargeLocators.ts
        registerInGuestCityLocators.ts
      household/
        householdServices/
          changeFamilyRelativeLocators.ts
        relocation/
          TransferInsideProvinceLocators.ts
          TransferOutsideProvinceLocators.ts
          changeMemberOfficeLocators.ts
          divorceLocators.ts
          marriageLicenseLocators.ts
          marriageRegistrationLocators.ts
          mojavezWeddingLocators.ts
        tax/
          guestCityMunicipalTaxLocators.ts
          municipalTaxLocators.ts
      identity/
        education/
          expirationOfStudentPermitLocators.ts
          studentPermitRegistrationLocators.ts
        identity/
          phoneNumberManagementLocators.ts
        subsidiaryServices/
          assetsLocators.ts
          insuranceLocators.ts
          referralFormLocators.ts
          supportingOrganization/
            removeSupportingOrganizationLocators.ts
            supportingOrganizationLocators.ts
      identityNewRegistrationLocators.ts
      irainianIdentityLocators.ts
      leavingTheCountryLocators.ts
      locators.ts
      myRequestsLocators.js
      planImplementation/
        issueCardLocators.ts
        planImplementationLocators.ts
      recordingDeathInformationLocators.ts
      recoveryOfAsylumCancellationLocators.ts
      revocationOfAsylumLocators.ts
      secondaryMenuCartableLocators.ts
      statusEventCheck/
        statusEventCheckLocators.ts
      supporting/
        supportLocators.ts
      tableLocators.ts
      trafficSheet/
        issuanceOfTrafficPermitLocators.ts
        trafficPermitExtensionLocators.ts
      userProfileLocators.js
      violationLocators.ts
      vulnerabilityManagementLocators.ts
    pages/
      adminWorkSpacePages/
        eventAcceptionPage.ts
      basicInformation/
        other/
          forbiddenCountryDivisionPage.ts
          licensePage.ts
          universitiePage.ts
        users/
          accessLevelPage.ts
          organizationalChartPage.ts
      biometricActionsPage.ts
      camp/
        campAdmission/
          campAdditionalPage.ts
          campPage.ts
        campAdmissionwithReturnPermitPage.ts
        createACampExclusionListPage.ts
        createAnExitListPage.ts
        exclusionList.js
        expiredInCampPage.ts
        finalizeDeportationPage.ts
        keepInCampPage.ts
        selfIntroductionCampAdmissionPage.ts
        transitAcceptance.js
      dashboard.js
      foreignNationalServices/
        selfIntroducingPage.ts
      generalClass/
        scanFileSection.js
      guestCity/
        createDischargePage.ts
        registerInGuestCityPage.ts
      household/
        householdServices/
          changeFamilyRelativePage.ts
        relocation/
          TransferInsideProvincePage.ts
          TransferOutsideProvincePage.ts
          changeMemberOfficePage.ts
          divorcePage.ts
          marriageLicensePage.ts
          marriageRegistrationPage.ts
          mojavezWeddingPage.ts
        tax/
          guestCityMunicipalTaxPage.ts
          municipalTaxPage.ts
      identity/
        education/
          expirationOfStudentPermitPage.ts
          studentPermitRegistrationPage.ts
        identity/
          VulnerabilityManagementPage.ts
          addressManagementPage.ts
          correctionOfIdentityInformationPage.ts
          identityNewRegistrationPage.ts
          iranianIdentityPage.ts
          phoneNumberManagementPage.ts
        revocationOfAsylum/
          banServicePage.ts
          crimePage.ts
          enterBorderPage.js
          enterToCountryPage.ts
          leavingTheCountryPage.ts
          recordingDeathInformationPage.ts
          recoveryOfAsylumCancellationPage.ts
          revocationOfAsylumPage.ts
          violationPage.ts
        subsidiaryServices/
          assetsPage.ts
          insurancePage.ts
          referralFormPage.ts
          supportingOrganization/
            removeSupportingOrganizationPage.ts
            supportingOrganizationPage.ts
        trafficSheet/
          issuanceOfTrafficPermitPage.ts
          trafficPermitExtensionPage.ts
      loginAsNewUserPage.ts
      loginPage.ts
      myRequestsPage/
        requestsTablePage.ts
      planImplementaion/
        issueCardPage.ts
        planImplementationPage.ts
      sidebar.ts
      statusEventCheck/
        statusEventCheckPage.ts
      supporting/
        readyMessagesPage.ts
        sendTicketPage.ts
      userProfile.js
    test/
      bdd/
        features/
          identityNewRegistration.feature
          smoke/
            camp/
              campAdmissionWithReturnPermit.feature
              createACampExclusionList.feature
              createAnExitList.feature
              selfIntroductionCampAdmission.feature
            planImplementation/
              issueCard.feature
              planImplementationNormalScenarioAmayesh18.feature
              planImplementationNormalScenarioNewEnter.feature
        step_definitions/
          identityNewRegistration.steps.ts
          smoke/
            camp/
              campAdmissionWithReturnPermit.steps.ts
              createACampExclusionList.steps.ts
              createAnExitList.steps.ts
              selfIntroductionCampAdmission.steps.ts
            common.steps.ts
            planImplementation/
              issueCard.steps.ts
              planImplementationCommon.steps.ts
              planImplementationNormalScenarioAmayesh18.steps.ts
              planImplementationNormalScenarioNewEnter.steps.ts
      fanctional/
      regression/
        basicInformation/
          other/
            addUniversityTest.cy.ts
            deleteUniversityTest.cy.ts
            editUniversityTest.cy.ts
            forbiddenCountryDivisionTest.cy.ts
            licenseTest.cy.ts
          users/
            accessLevelTest.cy.ts
            organizationalChartTest.cy.ts
        camp/
          campAdmissionHelpTest.cy.ts
          campAdmissionTest.cy.ts
          campAdmissionwithReturnPermitTest.cy.ts
          createACampExclusionListTest.cy.ts
          createAnExitListTest.cy.ts
          expiredOfCampTest.cy.ts
          keepInCampTest.cy.ts
          selfIntroductionCampAdmissionTest.cy.ts
        foreignNationalServices/
          selfIntroducingTest.cy.ts
        guestCity/
          createDischargeTest.cy.ts
          registerInGuestCityTest.cy.ts
        household/
          householdServices/
            changeFamilyRelativeTest.cy.ts
          relocation/
            TransferInsideProvinceTest.cy.ts
            TransferOutsideProvinceTest.cy.ts
            changeMemberOfficeTest.cy.ts
            divorceTest.cy.ts
            marriageLicenseTest.cy.ts
            marriageRegistrationTest.cy.ts
            mojavezWeddingTest.cy.ts
          tax/
            guestCityMunicipalTaxTest.cy.ts
            municipalTaxTest.cy.ts
        identity/
          education/
            expirationOfStudentPermitTest.cy.ts
            studentPermitRegistrationDuplicateLicenseTest.cy.ts
          identity/
            addressManagementTest.cy.ts
            correctionOfIdentityInformationWithConfirmationbirthDateTest.cy.ts
            existingHouseholdTest.cy.ts
            existingHouseholdTestcp.cy.ts
            existingHouseholdWithEventAcceptTest.cy.ts
            identityMultiRegistrationTest
            identityMultiRegistrationWithEventAcceptTest
            identityMultiRegistrationInManagerAccountTest.cy.ts
            identityNewRegistrationTest.cy.ts
            identityNewRegistrationWithEventAcceptTest
            identityNewRegistrationWithEventRejectTest
            identityNewRegistrationWithEventReturnTest
            irainianIdentityTest.cy.ts
            phoneNumberManagementTest.cy.ts
            vulnerabilityManagementTest.cy.ts
          revocationOfAsylum/
            banServiceWithConfirmationTest.cy.ts
            banServiceWithoutConfirmationTest.ts
            crimeWithConfirmationTest.cy.ts
            enterToCountryTest.cy.ts
            leavingTheCountryWithConfirmationTest.cy.ts
            recordingDeathInformationWithConfirmationTest.cy.ts
            recordingDeathInformationWithoutConfirmationTest.ts
            revocationOfAsylumWithConfirmationTest.cy.ts
            undoCancelationCardTest.cy.ts
            undoIssuanceOfTrafficPermitTest.cy.ts
            undoOtherTest.cy.ts
            undoRevocationOfAsylumTest.cy.ts
            violationWithConfirmationTest.cy.ts
          subsidiaryServices/
            assetsTest.cy.ts
            insuranceTest.cy.ts
            referralFormTest.cy.ts
            supportingOrganization/
              addSupportingOrganizationTest.cy.ts
              removeSupportingOrganizationAcceptTest.cy.ts
          trafficSheet/
            issuanceOfTrafficPermitTravelTest.cy.ts
            trafficPermitExtensionTest.cy.ts
        login/
          loginAsNewUserTest.cy.ts
          loginTest.cy.ts
        planImplementation/
          issueCardTest.cy.ts
          planImplementationNormalScenarioAmayesh18Test.cy.ts
          planImplementationNormalScenarioNewEnterTest.cy.ts
        statusEventCheckAndEventAcception/
          statusEventCheckAndEventAcceptionTest.cy.ts
        supporting/
          readyMessagesTest.cy.ts
          sendTicketTest.cy.ts
        tabel/
          myRequests.cy.ts
      sanity/
      smoke/
        camp/
          campAdmissionwithReturnPermitTest.cy.ts
          createACampExclusionListTest.cy.ts
          createAnExitListTest.cy.ts
          selfIntroductionCampAdmissionTest.cy.ts
        planImplementation/
          issueCardTest.cy.ts
          planImplementationNormalScenarioAmayesh18Test.cy.ts
          planImplementationNormalScenarioNewEnterTest.cy.ts
  fixtures/
    campPage/
      finalizeDeportationDataJson.json
    file/
      file.png
    identity/
      addressDataJson.json
      documentDataJson.json
      personalDataJson.json
    usersJson.json
  support/
    commands.ts
    db/
      member.queries.ts
    e2e.ts
    enums/
      eventStatusEnum.enum.ts
    flows/
      banAndUndoFlow.js
      marriageRegistrationFlow.ts
    handler/
      eventStatusHandler.handler.ts
    heplers/
      address/
        createAddressForExistingHouseholdHelper.helper.ts
      approval/
        setupApprovalWorkflowHelper.helper.ts
      basicInformation/
        other/
          addUniversityHelper.helper.ts
          forbiddenCountryDivisionHelper.helper.ts
          licenseHelper.helper.ts
        users/
          accessLevelHelper.helper.ts
      camp/
        campAdmissionHelper.helper.ts
        campAdmissionWithReturnPermitHelper.helper.ts
        campExclusionListHelper.helper.ts
        campExitListHelper.helper.ts
        expiredOfCampHelper.helper.ts
        keepInCampHelper.helper.ts
        selfIntroductionCampHelper.helper.ts
      guestCity/
        createDischargeHelper.helper.ts
        registerInGuestCityHelper.helper.ts
      household/
        householdServices/
          changeFamilyRelativeHelper.helper.ts
        relocation/
          TransferInsideProvinceHelper.helper.ts
          TransferOutsideProvinceHelper.helper.ts
          changeMemberOfficeHelper.helper.ts
          divorceHelper.helper.ts
          marriageLicenseHelper.helper.ts
          marriageRegistrationHelper.helper.ts
          mojavezWeddingHelper.helper.ts
        tax/
          guestCityMunicipalTax.cy.js
          municipalTaxHelper.helper.ts
      identity/
        education/
          expirationOfStudentPermitHelper.helper.ts
          studentPermitRegistrationHelper.helper.ts
        foreignNationalServices/
          selfIntroducingHelper.helper.ts
        identity/
          correctionOfIdentityInformationHelper.helper.ts
          identityNewRegistrationHelper.helper.ts
          phoneNumberManagementHelper.helper.ts
        issuanceOfTrafficPermit/
          issuanceOfTrafficPermitHelper.helper.ts
          trafficPermitExtensionHelper.helper.ts
        revocationOfAsylum/
          banServiceHelper.helper.ts
          crimeHelper.helper.ts
          enterToCountryHelper.helper.ts
          leavingTheCountryHelper.helper.ts
          recordingDeathInformationHelper.helper.ts
          revocationOfAsylumHelper.helper.ts
        subsidiaryServices/
          assetsHelper.helper.ts
          insuranceHelper.helper.ts
          referralFormHelper.helper.ts
          supportingOrganization/
            addSupportingOrganizationHelper.helper.ts
            removeSupportingOrganizationHelper.helper.ts
      planImplementationHelper.helper.ts
      recoveryOfAsylumCancellationHelper.helper.ts
      statusEventCheckHelper.helper.ts
      supporting/
        readyMessagesHelper.helper.ts
        sendTicketHelper.helper.ts
    index.d.ts
    mappers/
      eventStatusMapper.mapper.ts
    types/
      addressDataJson.d.ts
      addressDataJson.ts
      biometricMode.types.ts
      documentDataJson.d.ts
      finalizeDeportationData.d.ts
      jalaali-js.d.ts
      personalDataJson.d.ts
      types.d.ts
      usersJson.d.ts
  utils/
    compareDetail/
      comparison.util.ts
      detailsSchema.util.ts
      objectPath.util.ts
    generateRandomNumber.ts
    generateRandomWords.ts
    nationalCodeGenerator.ts
    persian-date.ts
    phoneNumberGenerator.ts
    postalCodeGenerator.ts
cypress.config.ts
cypress.env.json
package-lock.json
package.json
scripts/
  allure/
    generate.js
    open.js
  generate-jsdoc.js
  jira-report.js
  run-all.js
  serve/
    copy.js
    index.js
    report.cmd
    report.ps1
    report.sh
skills-lock.json
tsconfig.json
\`\`\`

## Layer Structure

| Layer | Path | Files | Sample Files |
|---|---|---|---|
| Locators | \`cypress/e2e/locators/\` | 58 | \`cypress/e2e/locators/addressManagementLocators.ts\`<br>\`cypress/e2e/locators/adminWorkSpaceLocators/eventAcceptionLocators.ts\`<br>\`cypress/e2e/locators/banServiceLocators.ts\` |
| Page Objects | \`cypress/e2e/pages/\` | 67 | \`cypress/e2e/pages/adminWorkSpacePages/eventAcceptionPage.ts\`<br>\`cypress/e2e/pages/basicInformation/other/forbiddenCountryDivisionPage.ts\`<br>\`cypress/e2e/pages/basicInformation/other/licensePage.ts\` |
| Tests (Smoke) | \`cypress/e2e/test/smoke/\` | 7 | \`cypress/e2e/test/smoke/camp/campAdmissionwithReturnPermitTest.cy.ts\`<br>\`cypress/e2e/test/smoke/camp/createACampExclusionListTest.cy.ts\`<br>\`cypress/e2e/test/smoke/camp/createAnExitListTest.cy.ts\` |
| Tests (Regression) | \`cypress/e2e/test/regression/\` | 74 | \`cypress/e2e/test/regression/basicInformation/other/addUniversityTest.cy.ts\`<br>\`cypress/e2e/test/regression/basicInformation/other/deleteUniversityTest.cy.ts\`<br>\`cypress/e2e/test/regression/basicInformation/other/editUniversityTest.cy.ts\` |
| Helpers | \`cypress/support/heplers/\` | 49 | \`cypress/support/heplers/address/createAddressForExistingHouseholdHelper.helper.ts\`<br>\`cypress/support/heplers/approval/setupApprovalWorkflowHelper.helper.ts\`<br>\`cypress/support/heplers/basicInformation/other/addUniversityHelper.helper.ts\` |
| Flows | \`cypress/support/flows/\` | 2 | \`cypress/support/flows/banAndUndoFlow.js\`<br>\`cypress/support/flows/marriageRegistrationFlow.ts\` |
| Support | \`cypress/support/\` | 67 | \`cypress/support/commands.ts\`<br>\`cypress/support/db/member.queries.ts\`<br>\`cypress/support/e2e.ts\` |
| Fixtures | \`cypress/fixtures/\` | 6 | \`cypress/fixtures/campPage/finalizeDeportationDataJson.json\`<br>\`cypress/fixtures/file/file.png\`<br>\`cypress/fixtures/identity/addressDataJson.json\` |
| Utils | \`cypress/utils/\` | 9 | \`cypress/utils/compareDetail/comparison.util.ts\`<br>\`cypress/utils/compareDetail/detailsSchema.util.ts\`<br>\`cypress/utils/compareDetail/objectPath.util.ts\` |
| Types | \`cypress/support/types/\` | 9 | \`cypress/support/types/addressDataJson.d.ts\`<br>\`cypress/support/types/addressDataJson.ts\`<br>\`cypress/support/types/biometricMode.types.ts\` |

## Naming Conventions

| Layer | Pattern | Example |
|---|---|---|
| Locators | \`{Pascal}Locators.ts\` | \`cypress/e2e/locators/addressManagementLocators.ts\` |
| Page Objects | \`{Pascal}Page.ts\` | \`cypress/e2e/pages/adminWorkSpacePages/eventAcceptionPage.ts\` |
| Tests (Smoke) | \`{Pascal}Test.cy.ts\` | \`cypress/e2e/test/smoke/camp/campAdmissionwithReturnPermitTest.cy.ts\` |
| Tests (Regression) | \`{Pascal}Test.cy.ts\` | \`cypress/e2e/test/regression/basicInformation/other/addUniversityTest.cy.ts\` |
| Helpers | \`{camel}Helper.helper.ts\` | \`cypress/support/heplers/address/createAddressForExistingHouseholdHelper.helper.ts\` |
| Flows | \`{camel}Flow.js\` | \`cypress/support/flows/banAndUndoFlow.js\` |
| Support | \`{camel}.ts\` | \`cypress/support/commands.ts\` |
| Fixtures | \`{Pascal}Json.json\` | \`cypress/fixtures/campPage/finalizeDeportationDataJson.json\` |
| Utils | \`{camel}.util.ts\` | \`cypress/utils/compareDetail/comparison.util.ts\` |
| Types | \`{camel}.ts\` | \`cypress/support/types/addressDataJson.d.ts\` |

## Coding Patterns

class-based Page Objects, singleton instance export, custom commands (getByCy), separate locator imports, exported helper functions, as const for literal types, UPPER_SNAKE_CASE constants

## Custom Cypress Commands

\`\`\`typescript
Cypress.Commands.add("login", ...)
Cypress.Commands.add("drag", ...)
Cypress.Commands.add("dismiss", ...)
Cypress.Commands.add("getByCy", ...)
Cypress.Commands.add("deleteFile", ...)
Cypress.Commands.add("deleteFolder", ...)
Cypress.Commands.add("deleteDownloadsFolder", ...)
Cypress.Commands.add("captureRequestCodes", ...)
Cypress.Commands.add("dbHealthCheck", ...)
Cypress.Commands.add("clickIfVisible", ...)
Cypress.Commands.add("fetchDynamicMenuIds", ...)
Cypress.Commands.add("getDynamicMenu", ...)
Cypress.Commands.add("extractUiDetails", ...)
\`\`\`

---

## Meta

\`\`\`json
{
  "outputPaths": {
    "test": "cypress/e2e/test/smoke",
    "testRegression": "cypress/e2e/test/regression",
    "page": "cypress/e2e/pages",
    "locators": "cypress/e2e/locators",
    "helper": "cypress/support/heplers",
    "bdd": "cypress/e2e/features",
    "bddSteps": "cypress/e2e/step-definitions",
    "flow": "cypress/support/flows",
    "utils": "cypress/utils",
    "fixture": "cypress/fixtures",
    "type": "cypress/support/types"
  },
  "namingPatterns": {
    "test": "{Pascal}Test.cy.ts",
    "page": "{Pascal}Page.ts",
    "locators": "{Pascal}Locators.ts",
    "helper": "{camel}Helper.helper.ts",
    "bdd": "{name}.feature",
    "bddSteps": "{Pascal}Steps.ts",
    "flow": "{camel}Flow.js",
    "utils": "{camel}.util.ts",
    "fixture": "{Pascal}Json.json",
    "type": "{camel}.ts",
    "testRegression": "{Pascal}Test.cy.ts"
  }
}
\`\`\`
`;
